### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by kerel-fs** [glidernet/ogn-ddb#11]
For reference: The AGPL was chosen for ogn-live (glidernet/ogn-live#6).
What are your thoughts? @snip @cunimb  @dbursem

**Comment by snip** [comment]
+1 for AGPL.

**Comment by dbursem** [comment]
I think AGPL is a good choice for the software (so +1), but a much more important question is how to licence the data. 

I think we should apply something like the ODBL to that. Maybe with a mailing to contributers notifying them of this decision.
http://opendatacommons.org/licenses/odbl/summary/

**Comment by snip** [comment]
For the data, why not just ODC-BY?
http://opendatacommons.org/licenses/by/summary/
ODBL may be too restrictive and may limit usage.

**Comment by dbursem** [comment]
I don't think ODbL would be too restrictive. For example OpenStreetMap uses it and there are endless possibilities for apps with OSM data. 
Example: It will be possible to use and publish DDB data as part of a third-party dataset, but it won't be allowed to restrict usage of that dataset other than the restrictions of the ODbL (I like this).
Also there won't be any restriction on using ODbL licensed data, for example to create tracking maps, APRS-clients and many other things. 

Nevertheless, i'm fine with ODC-BY too. I think the most important is to be clear about the licensing, no matter what license we use. We now have the same ambiguity of having no license info at all that made it necessary to create the DDB in the first place.

**Comment by snip** [comment]
@kerel-fs @cunimb ok for ODC-BY?

**Comment by snip** [comment]
Fixed in 381f906b7c760dacf8b2bf03cac32d1d73dba07e
