### ISSUE TITLE
Field Definitions

### ISSUE THREAD

**Issue by tobiz** [glidernet/ogn-ddb#16]
Could you also add definitions for all fields including AIRCRAFT_TYPE which seems to be an integer (1:6?) but what do the integer values _mean_?  Is this defined elsewhere? If so could a reference be included to the meanings?

**Comment by kerel-fs** [comment]
Indeed, the aircraft_type is an integer, the values are hard-coded currently:
https://github.com/glidernet/ogn-ddb/blob/master/index.php#L87

With a new API it's planned to expose this data, see #15 / [API-endpoints.md](https://github.com/kerel-fs/ogn-ddb/blob/2cefa780b6e4b3a70dfb324521bb6f33e019bda9/API-endpoints.md#list-aircraft-models).

**Comment by tobiz** [comment]
Thanks
