### ISSUE TITLE
Create password page when error while resseting password

### ISSUE THREAD

**Issue by snip** [glidernet/ogn-ddb#33]
If user do an error (wrong captcha, not existing email, ...) while reseting password it is redirected to account creation instead of password recovery page.

**Comment by acasadoalonso** [comment]
Seb,
Corrected, tested, it is to change fillinuser() by fillinuserforgot() when an error is found resetting the password.
PR ready to apply, however some conflict exist becuase Seb's changes.
I may need to rebase.
AC/.

**Comment by acasadoalonso** [comment]
Fixed ... PR ready ...

AC/.

**Comment by snip** [comment]
Already fixed.
