### ISSUE TITLE
json download broken

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/ogn-ddb#38]
http://ddb.glidernet.org/download/?j=1 should return the ddb in json format. This does not work anymore. #

**Comment by acasadoalonso** [comment]
The std format it seems to work, I will take a look on the JSON format ...

AC/.

**Comment by acasadoalonso** [comment]
Folks,

It seems that is not accepting the ?j=1 url parameter when it is alone … the copy that I have on my home server is not having that problem  … 
But with other parameter is OK.
http://ddb.glidernet.org/download/index.php?cn=K5&j=1 <http://ddb.glidernet.org/download/index.php?cn=K5&j=1> 
{"devices":[{"device_type":"I","device_id":"4407F9","aircraft_model":"LS-4","registration":"OE-5391","cn":"K5","tracked":"Y","identified":"Y"},{"device_type":"I","device_id":"4B4B3A","aircraft_model":"LS-4","registration":"HB-1683","cn":"K5","tracked":"Y","identified":"Y"},{"device_type":"F","device_id":"DD9124","aircraft_model":"Duo Discus","registration":"D-4010","cn":"K5","tracked":"Y","identified":"Y"},{"device_type":"F","device_id":"DD9570","aircraft_model":"SZD-50 Puchacz","registration":"OE-5424","cn":"K5","tracked":"Y","identified":"Y"},{"device_type":"F","device_id":"DDD9F1","aircraft_model":"ASW-27","registration":"OK-2727","cn":"K5","tracked":"Y","identified":"Y"},{"device_type":"F","device_id":"DDE48A","aircraft_model":"Janus Ce","registration":"D-2520","cn":"K5","tracked":"Y","identified":"Y"},{"device_type":"F","device_id":"DDEC8E","aircraft_model":"LS-4","registration":"HB-1683","cn":"K5","tracked":"Y","identified":"Y"},{"device_type":"F","device_id":"DF10F9","aircraft_model":"Duo Discus xlt","registration":"D-KWWH","cn":"K5","tracked":"Y","identified":"Y"}]}
It seems to me that is a problem with the size of the output buffer, perhaps too many entries now. I will check the function: echo json_encode($output); We need to add: echo json_last_error_msg();  
After calling Json_encode()… that way we will see what is the problem. perhaps we have some data with non UTF-8 data.

Cheers.
AC/.

**Comment by snip** [comment]
> perhaps we have some data with non UTF-8 data.

You were right.
Error message related to the `json_encode` is:
`Malformed UTF-8 characters, possibly incorrectly encoded`

PR is welcome :)
Thanks

**Comment by acasadoalonso** [comment]
I will submit the PR tonite
However we need to find out the data that is incorrect on the database
I will try to do an scan and find it out 

Enviado desde mi iPhone.
AC/.

**Comment by Meisterschueler** [comment]
The problem is here:
'F','DD8E53','L-60 Brigad�r','OM-LKL','LKL','Y','Y'

**Comment by snip** [comment]
I changed the value from `L-60 Brigadýr` to `L-60 Brigadyr` in the database.
The json format is working again.

**Comment by snip** [comment]
Should we keep this open until we have a fix on code side or do you think we can close this issue?

**Comment by Meisterschueler** [comment]
Best would be if the ddb could handle utf-8 strings. But since the Brigadýr is a not so common aircraft I think removing the accent and keep out non-ascii chars is also a good solution.

**Comment by clementallen** [comment]
This seems to be an issue again :( @snip @Meisterschueler

**Comment by snip** [comment]
Fixed again.
Was coming from Rhönbussard renamed as Rhonbussard.
Thanks for the head-up.

**Comment by clementallen** [comment]
No problem @snip, although I'm certain this will come back again - is it worth looking at a more permanent fix?

**Comment by snip** [comment]
It is only coming when i add new aircraft type ... and forget that i should not add any special chars.
Yes having a permanent solution is better, but i clearly not have time for that.
If someone can propose a pull request he is welcome.
