### ISSUE TITLE
Enable compression for download

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/ogn-ddb#41]
For ddb website gzip compression is enabled, but for download (http://ddb.glidernet.org/download/) it is disabled. This affects the android app "OGN viewer", so each startup need 585kB instead of 150kB.

**Comment by snip** [comment]
Nothing is disabled in Nginx config.
So maybe something need to be done in the PHP side?
https://github.com/glidernet/ogn-ddb/blob/master/download/index.php

Maybe linked to https://serverfault.com/questions/462437/nginx-gzip-did-not-work-on-php-js-and-css-processors

**Comment by snip** [comment]
"OGN viewer" is using the json output or csv one?

**Comment by snip** [comment]
Current NGinx gzip configuration from /etc/nginx/nginx.conf (which is the default one):
>         ##
>         # Gzip Settings
>         ##
> 
>         gzip on;
>         gzip_disable "msie6";
>
>         # gzip_vary on;
>         # gzip_proxied any;
>         # gzip_comp_level 6;
>         # gzip_buffers 16 8k;
>         # gzip_http_version 1.1;
>         # gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

**Comment by Meisterschueler** [comment]
I just checked the csv ddb download site "http://ddb.glidernet.org/download/" with https://checkgzipcompression.com and I got "GZIP is not enabled :("

"OGN Viewer" uses ogn-java-commons, so it gets the ddb from site above

**Comment by kerel-fs** [comment]
The default for `gzip_types` in nginx is `text/html` (souce: [nginx-doc: http_gzip_module](https://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_types)).
- The resource <http://ddb.glidernet.org/download/> has `Content-Type: text/plain; charset="UTF-8"`
- The resource <http://ddb.glidernet.org/> has `Content-Type: text/html`
- The resource <http://ddb.glidernet.org/download/?j=1> has `Content-Type: application/json`

So, it's probably enough to set the option `gzip_types` accordingly.

**Comment by snip** [comment]
I uncommented the following line from `/etc/nginx/nginx.conf` and it seems to be ok now according to https://checkgzipcompression.com (thanks for this link).
> gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

Is it ok for you @Meisterschueler ?

**Comment by Meisterschueler** [comment]
Thank you very much
