### ISSUE TITLE
Allow more characters into CN field / Registration

### ISSUE THREAD

**Issue by laurentchivot** [glidernet/ogn-ddb#52]
At first ddb has been conceived for gliders , nowadays ddb welcomes new aircraft types such as ultralight powered aircrafts. In France , these aircrafts have two "callsigns" the radio one F-Jxxx and the visual id sign on the wing two digits reflecting a geographical origin and letters.
For safety reason , it is better to be able to konw these two regisytration id's.

Could it be possible to extend the CN field up to 6 hex characters ? one alternative could be to allow Registration up to 14 hex characters

Regards

**Comment by acasadoalonso** [comment]
Laurent,

The new design of the OGN DDB V2.0 the ID assigned is 64 chars long and it is designed to be used for all kind of devices that are now on the OGN Network like SPOT/SPIDER/INREACH/OUDIES/FLYMASTER/PAW/ .... etc ...

Cheers.

AC/.

**Comment by laurentchivot** [comment]
Hi Angel, you mean the DeviceID ?

**Comment by acasadoalonso** [comment]
Yes on the new version, can be until 64 chars

AC/.

**Comment by laurentchivot** [comment]
With all the respect, putting all the info in one field is not a good practice , and is not clear for users. 

no mods scheduled in OGN DDB V2.0 for Registration and CN ?

**Comment by acasadoalonso** [comment]
No my friend, it is not all the info in one field, it is that some of the devices require a longer ID like SPOT or SPIDER or InReach etc ... so the idea of be 24bits - 6 chars come from Flarm, at that time it made sense, not any more ... the rest of fields remains unchanged 
See the doc at: https://github.com/acasadoalonso/ogn-ddb/blob/master/docs/OGN%20DDB%20proposal%20V2.04.pdf 

It will be a new API that it will allow to apps like yours to add dynamically devices to the OGN DDB

Cheers.

AC/.

**Comment by laurentchivot** [comment]
Thanks for sharing your proposition, i'll have a deeper look at it. The API is definitely a great news. let's close this issue for the moment ;-)

Regards
Laurent
