### ISSUE TITLE
Table display squiffy after expiration clock added

### ISSUE THREAD

**Issue by scorer** [glidernet/ogn-ddb#58]
1) I just took a look at the OGN ddb to see if there was anything to tell when a registration will expire and found that it appears to have as problem with formatting the display.
You appear to have added an expiry clock ,  but the table doesn’t have enough rows to display correctly [or rather the expiration label is in the wrong row in column 1  to match the clock in column 2 ]

2)  Sign in seems to no longer remember my credentials ( at least not on my iPad or iPhone)

**Comment by snip** [comment]
Indeed it seems there is an issue somewhere about formating:
<img width="359" alt="image" src="https://github.com/glidernet/ogn-ddb/assets/466133/1860c2db-42df-4908-a94d-924978ad0af4">
Working on it ....

But there should be no issue about credential recording.

**Comment by snip** [comment]
@skizzofly if you want to have a look ...

**Comment by snip** [comment]
@skizzofly if you want to have a look ...

**Comment by scorer** [comment]
Doesn’t look very fixed to me! Sent from my iPhoneOn 18 Apr 2024, at 19:43, Sebastien Chaumontet ***@***.***> wrote:﻿
Closed #58 as completed via 8cd5a7b.

**Comment by snip** [comment]
I just put in production right now. It seems you were too fast.
On my side it looks much beter:
<img width="379" alt="image" src="https://github.com/glidernet/ogn-ddb/assets/466133/bda9f48e-52d8-4e2b-b530-8cc9cd66158e">

Can you pelase check again?

**Comment by scorer** [comment]
Yes it lines up nicely now! Thank you Sent from my iPhoneOn 18 Apr 2024, at 19:50, Sebastien Chaumontet ***@***.***> wrote:﻿
I just put in production right now. It seems you were too fast.
On my side it looks much beter:
image.png (view on web)
Can you pelase check again?
