### ISSUE TITLE
Incorrect charset at email after posting for new account

### ISSUE THREAD

**Issue by snip** [glidernet/ogn-ddb#9]
![image](https://cloud.githubusercontent.com/assets/466133/14128094/e757c618-f61d-11e5-93fa-53a3839e66ba.png)

**Comment by snip** [comment]
Tentative fix in pull request https://github.com/glidernet/ogn-ddb/pull/10

**Comment by kerel-fs** [comment]
In some templates the HTML-meta-tag Content-Type is not set to utf-8, causing this issue.

There are three possible solutions:
1. Set default encoding to utf-8 in the web server configuration
2. Set HTTP-Content-Type-Header in each php-File
3. Set HTML-meta-tag Content-Type in each HTML-template (via a single base template)

I would recommend option 1 or a combination of option 1 and 2 to fix this issue.
